thymeleaf:
  cache: false
  check-template-location: false
  enabled: true
  prefix: classpath:/templates
  suffix: .html
  view-names: /html/*

  spring:
    resources:
      static-locations: classpath:/static/
